version: "3"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - "frontend"
    restart: on-failure
  db:
    image: postgres:9.4
    environment:
        POSTGRES_PASSWORD: mypass
        POSTGRES_HOST_AUTH_METHOD: trust
        PGDATA: /var/lib/postgresql/data/pgdata
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - "backend"
    restart: on-failure
  vote:
    image: bretfisher/examplevotingapp_vote
    ports:
      - "5000:80"
    networks:
      - "frontend"
    depends_on:
      - "redis"
    restart: on-failure
  result:
    image: bretfisher/examplevotingapp_result
    ports:
      - "5001:80"
    networks:
      - "backend"
    depends_on:
      - "db"
    restart: on-failure
      
  worker:
    image: bretfisher/examplevotingapp_worker
    networks:
      - "frontend"
      - "backend"
    restart: on-failure
   
        
        
networks:
    backend:
        driver: overlay
    frontend:
        driver: overlay
volumes:
    db-data:
        driver: local
